import { useEffect, useState } from "react";
import api from "../../services/api";
import { getCurrentUser } from "../../services/authService";
import { formatDate } from "../../utils/dateUtils";

export default function StaffReceipts() {
  const [receipts, setReceipts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [summary, setSummary] = useState({ count: 0, total: 0 });

  const user = getCurrentUser();
  const branchId = user?.branch_id;

  useEffect(() => {
    if (branchId) {
      loadReceipts();
    }
  }, [branchId, startDate, endDate]);

  const loadReceipts = async () => {
    setLoading(true);
    try {
      const params = {
        date_from: startDate,
        date_to: endDate
      };

      const salesRes = await api.sales.getByBranch(branchId, params);
      setReceipts(salesRes.transactions || []);
      setSummary({
        count: salesRes.transactions?.length || 0,
        total: salesRes.transactions?.reduce((sum, t) => sum + t.total_amount, 0) || 0
      });

    } catch (err) {
      console.error("Failed to load receipts", err);
    }
    setLoading(false);
  };

  /* ================= PRINT ALL SALES ================= */
  const printAllSales = () => {
    if (!receipts.length) return;
    const win = window.open("", "_blank");
    const now = new Date();

    const styles = `<style>
      body { font-family: "Segoe UI", Arial, sans-serif; padding: 20px; color: #111; font-size: 11px; }
      .hdr { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 15px; }
      .hdr h2 { margin: 0; font-size: 16px; }
      .hdr p { margin: 2px 0; font-size: 10px; }
      .summary-box { display: flex; justify-content: space-around; background: #f8fafc; border: 1px solid #e2e8f0; padding: 10px; margin-bottom: 15px; border-radius: 4px; }
      .summary-item { text-align: center; }
      .summary-item b { display: block; font-size: 14px; color: #1e293b; }
      table { width: 100%; border-collapse: collapse; margin: 10px 0; }
      th { background: #f1f5f9; border: 1px solid #cbd5e1; padding: 6px; text-align: left; font-size: 9px; text-transform: uppercase; }
      td { border: 1px solid #cbd5e1; padding: 5px; vertical-align: top; }
      .r { text-align: right; }
      .ftr { margin-top: 20px; text-align: center; font-size: 9px; color: #64748b; border-top: 1px dashed #cbd5e1; padding-top: 10px; }
    </style>`;

    const header = `<div class="hdr">
      <h2>RETAIL STORE - CONSOLIDATED SALES REPORT</h2>
      <p><b>Branch:</b> ${user?.branch_name || 'Main'}</p>
      <p><b>Period:</b> ${formatDate(new Date(startDate))} to ${formatDate(new Date(endDate))}</p>
      <p><b>Generated On:</b> ${now.toLocaleString()}</p>
    </div>`;

    const summaryHtml = `<div class="summary-box">
      <div class="summary-item">Transactions: <b>${summary.count}</b></div>
      <div class="summary-item">Total Revenue: <b>₹${summary.total.toFixed(2)}</b></div>
    </div>`;

    let table = '<table><thead><tr><th>Date</th><th>Bill No</th><th>Items</th><th>Payment</th><th class="r">Amount</th></tr></thead><tbody>';
    receipts.forEach(r => {
      const itemsText = r.items?.map(i => `${i.product_name} x${i.quantity}`).join(', ') || 'No Items';
      table += `<tr>
        <td>${formatDate(r.transaction_date)}</td>
        <td>#${r.transaction_id}</td>
        <td style="max-width:300px">${itemsText}</td>
        <td style="text-transform:uppercase">${r.payment_method}</td>
        <td class="r">₹${r.total_amount.toFixed(2)}</td>
      </tr>`;
    });
    table += '</tbody></table>';

    const footer = `<div class="ftr">
      <p>End of Report | Page 1 of 1</p>
      <p>Generated by ${user?.name || 'Staff'}</p>
    </div>`;

    win.document.write(`<html><head><title>Sales_Report_${startDate}_to_${endDate}</title>${styles}</head><body>${header}${summaryHtml}${table}${footer}</body></html>`);
    win.document.close();
    win.print();
  };

  /* ================= PRINT RECEIPT ================= */
  const printReceipt = (sale) => {
    const win = window.open("", "_blank", "width=350,height=600");

    if (!win) {
      alert("Receipt printing was blocked by your browser.\nPlease allow popups for this site.");
      return;
    }

    const transaction_id = sale.transaction_id || "ERR";
    const transaction_date = sale.transaction_date ? new Date(sale.transaction_date) : new Date();
    const total_amount = Number(sale.total_amount || 0);
    const discount = Number(sale.discount || 0);
    const paymentMethod = sale.payment_method;
    const items = sale.items || [];

    // GST breakup
    const gstBreakup = {};
    items.forEach(item => {
      const rate = item.gst_percent || 0;
      if (!gstBreakup[rate]) gstBreakup[rate] = { taxable: 0, cgst: 0, sgst: 0 };
      const price = Number(item.unit_price || 0);
      const qty = Number(item.quantity || 0);
      const itemTotal = price * qty;
      const taxable = itemTotal / (1 + rate / 100);
      const taxAmt = itemTotal - taxable;
      gstBreakup[rate].taxable += taxable;
      gstBreakup[rate].cgst += taxAmt / 2;
      gstBreakup[rate].sgst += taxAmt / 2;
    });

    const totalSavings = discount;
    const roundedTotal = Math.round(total_amount);
    const roundOff = roundedTotal - total_amount;
    const totalQty = items.reduce((s, i) => s + Number(i.quantity || 0), 0);
    const grossAmt = items.reduce((s, i) => s + (Number(i.unit_price || 0) * Number(i.quantity || 0)), 0);

    // Amount in words (Indian)
    const numberToWords = (num) => {
      const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
        'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
      const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
      if (num === 0) return 'Zero';
      const n = Math.abs(Math.round(num));
      if (n < 20) return ones[n];
      if (n < 100) return tens[Math.floor(n / 10)] + (n % 10 ? ' ' + ones[n % 10] : '');
      if (n < 1000) return ones[Math.floor(n / 100)] + ' Hundred' + (n % 100 ? ' and ' + numberToWords(n % 100) : '');
      if (n < 100000) return numberToWords(Math.floor(n / 1000)) + ' Thousand' + (n % 1000 ? ' ' + numberToWords(n % 1000) : '');
      if (n < 10000000) return numberToWords(Math.floor(n / 100000)) + ' Lakh' + (n % 100000 ? ' ' + numberToWords(n % 100000) : '');
      return numberToWords(Math.floor(n / 10000000)) + ' Crore' + (n % 10000000 ? ' ' + numberToWords(n % 10000000) : '');
    };

    // Monospace helpers
    const L = 42;
    const dash = '-'.repeat(L);
    const dblLine = '='.repeat(L);
    const center = (txt) => { const pad = Math.max(0, Math.floor((L - txt.length) / 2)); return ' '.repeat(pad) + txt; };
    const leftRight = (l, r) => l + ' '.repeat(Math.max(1, L - l.length - r.length)) + r;

    // Build item lines
    let itemLines = '';
    let sno = 0;
    items.forEach(i => {
      sno++;
      const name = (i.product_name || i.name || 'Item').length > 24 ? (i.product_name || i.name || 'Item').substring(0, 22) + '..' : (i.product_name || i.name || 'Item');
      const price = Number(i.unit_price || 0);
      const qty = Number(i.quantity || 0);
      const amt = (price * qty).toFixed(2);
      const gstTag = (i.gst_percent || 0) + '%';
      itemLines += sno + '. ' + name;
      if (i.is_b1g1) itemLines += ' (B1G1)';
      itemLines += '\n';
      itemLines += '   ' + qty + ' x ' + price.toFixed(2) + ' = ' + amt + '  [' + gstTag + ']\n';
    });

    // GST breakup lines
    let gstLines = '';
    gstLines += leftRight('GST%   Taxable    CGST     SGST', '') + '\n';
    gstLines += dash + '\n';
    let totTaxable = 0, totCGST = 0, totSGST = 0;
    Object.keys(gstBreakup).sort((a, b) => Number(a) - Number(b)).forEach(rate => {
      const g = gstBreakup[rate];
      totTaxable += g.taxable; totCGST += g.cgst; totSGST += g.sgst;
      gstLines += (rate + '%').padEnd(7) + g.taxable.toFixed(2).padStart(9) + g.cgst.toFixed(2).padStart(9) + g.sgst.toFixed(2).padStart(9) + '\n';
    });
    gstLines += dash + '\n';
    gstLines += 'Total'.padEnd(7) + totTaxable.toFixed(2).padStart(9) + totCGST.toFixed(2).padStart(9) + totSGST.toFixed(2).padStart(9) + '\n';

    // Discount line
    let discLine = '';
    if (discount > 0) discLine = leftRight('Less: Discount:', '-Rs.' + discount.toFixed(2)) + '\n';

    // Round off
    let roundLine = '';
    if (Math.abs(roundOff) >= 0.01) {
      roundLine = leftRight('Round Off', (roundOff >= 0 ? '+' : '') + roundOff.toFixed(2)) + '\n';
    }

    // Savings
    let savingsLine = '';
    if (totalSavings > 0) {
      savingsLine = '\n' + center('** You Saved Rs.' + totalSavings.toFixed(2) + ' **') + '\n';
    }

    // Calculate total GST
    const totalGST = totCGST + totSGST;

    // Date/time from transaction
    const dateStr = formatDate(transaction_date);
    const timeStr = transaction_date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true });

    // Full receipt
    const receipt =
      center('RETAIL STORE') + '\n' +
      center('Branch: ' + (user?.branch_name || 'Main')) + '\n' +
      center('4-143, Srinagar Colony, Vijayawada - 520001') + '\n' +
      center('GSTIN: 37XXXXX0000X1ZX') + '\n' +
      dblLine + '\n' +
      center('TAX INVOICE') + '\n' +
      dblLine + '\n' +
      leftRight('Bill No: ' + transaction_id, 'Date: ' + dateStr) + '\n' +
      leftRight('Cashier: ' + (user?.name || 'Staff'), 'Time: ' + timeStr) + '\n' +
      dash + '\n' +
      leftRight('ITEM', 'QTY x RATE = AMT [GST]') + '\n' +
      dash + '\n' +
      itemLines +
      dash + '\n' +
      leftRight('Total Items: ' + items.length, 'Total Qty: ' + totalQty) + '\n' +
      dash + '\n' +
      leftRight('Gross Amount:', 'Rs.' + grossAmt.toFixed(2)) + '\n' +
      discLine +
      leftRight('GST (Tax):', 'Rs.' + totalGST.toFixed(2)) + '\n' +
      roundLine +
      dblLine + '\n' +
      leftRight('NET PAYABLE:', 'Rs.' + roundedTotal.toFixed(2)) + '\n' +
      dblLine + '\n' +
      'Rs. ' + numberToWords(roundedTotal) + ' Only' + '\n' +
      dash + '\n' +
      '\n' +
      center('--- GST BREAKUP ---') + '\n' +
      gstLines +
      dash + '\n' +
      '\n' +
      leftRight('Payment:', (paymentMethod || 'cash').toUpperCase()) + '\n' +
      leftRight('Amount Paid:', 'Rs.' + roundedTotal.toFixed(2)) + '\n' +
      dash + '\n' +
      savingsLine +
      '\n' +
      center('Thank you! Visit Again') + '\n' +
      center('Goods once sold will not be taken back') + '\n' +
      center('E. & O.E.') + '\n' +
      '\n' +
      center('--- Authorized Signatory ---') + '\n' +
      '\n' +
      center('Computer Generated Invoice') + '\n';

    // Build HTML
    const html = '<!DOCTYPE html><html><head>' +
      '<title>Invoice #' + transaction_id + '</title>' +
      '<style>' +
      '* { margin:0; padding:0; }' +
      'body { font-family: "Courier New", "Lucida Console", monospace; font-size: 12px; padding: 5px; width: 302px; color: #000; line-height: 1.4; }' +
      'pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; font-size: inherit; margin: 0; }' +
      '@media print { body { width: 100%; padding: 2px; } }' +
      '</style>' +
      '</head><body>' +
      '<pre>' + receipt + '</pre>' +
      '</body></html>';

    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => {
      win.print();
      win.close();
    }, 250);
  };

  return (
    <div style={{ padding: '0 20px 20px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <h2>🧾 Sales Receipts</h2>
        <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '5px', background: '#fff', padding: '4px 8px', borderRadius: '6px', border: '1px solid #cbd5e1' }}>
            <span style={{ fontSize: '12px', color: '#64748b' }}>From:</span>
            <input
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              style={{ padding: '4px', border: 'none', fontSize: '13px' }}
            />
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '5px', background: '#fff', padding: '4px 8px', borderRadius: '6px', border: '1px solid #cbd5e1' }}>
            <span style={{ fontSize: '12px', color: '#64748b' }}>To:</span>
            <input
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              style={{ padding: '4px', border: 'none', fontSize: '13px' }}
            />
          </div>
          <button className="secondary-btn" onClick={printAllSales} disabled={loading || !receipts.length} style={{ padding: '8px 15px', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <i className="fas fa-print"></i> Print All Sales
          </button>
          <button className="primary-btn" onClick={loadReceipts} disabled={loading} style={{ padding: '8px 15px' }}>
            {loading ? "Refreshing..." : "🔄 Refresh"}
          </button>
        </div>
      </div>

      {/* SUMMARY CARDS */}
      <div className="dashboard-grid" style={{ marginBottom: '25px', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))' }}>
        <div className="data-box" style={{ borderLeft: '4px solid #10b981' }}>
          <h4>💰 Period Revenue</h4>
          <div className="value">₹{summary.total.toFixed(2)}</div>
        </div>
        <div className="data-box" style={{ borderLeft: '4px solid #3b82f6' }}>
          <h4>🧾 Transactions</h4>
          <div className="value">{summary.count}</div>
        </div>
      </div>

      <div className="table-card">
        {receipts.length === 0 ? (
          <div style={{ padding: '40px', textAlign: 'center', color: '#64748b' }}>
            <i className="fas fa-receipt" style={{ fontSize: '48px', marginBottom: '16px', opacity: 0.5 }}></i>
            <p>No receipts found for this period.</p>
          </div>
        ) : (
          <div className="table-responsive">
            <table>
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Date & Time</th>
                  <th>Payment</th>
                  <th>Items</th>
                  <th>Amount</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {receipts.map(r => (
                  <tr key={r.transaction_id}>
                    <td><span style={{ fontWeight: 600 }}>#{r.transaction_id}</span></td>
                    <td>
                      <div>{formatDate(r.transaction_date)}</div>
                      <div style={{ fontSize: '11px', color: '#64748b' }}>{new Date(r.transaction_date).toLocaleTimeString()}</div>
                    </td>
                    <td>
                      <span className={`stock-badge ${r.payment_method === 'cash' ? 'ok' : 'low'}`}
                        style={{ textTransform: 'uppercase', fontSize: '11px' }}>
                        {r.payment_method}
                      </span>
                    </td>
                    <td>{r.items?.length || 0} items</td>
                    <td style={{ fontWeight: 700 }}>₹{r.total_amount.toFixed(2)}</td>
                    <td>
                      <button
                        className="secondary-btn"
                        style={{ padding: '6px 12px', fontSize: '12px' }}
                        onClick={() => printReceipt(r)}
                      >
                        <i className="fas fa-print"></i> Print
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
