"""add return fields to transaction items

Revision ID: 0dd4309dcfce
Revises: b7c881cd8ec8
Create Date: 2026-03-07 23:20:38.483925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd4309dcfce'
down_revision = 'b7c881cd8ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_returned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('is_returned')

    # ### end Alembic commands ###
