"""Add interview_status to User

Revision ID: 10c579c861c3
Revises: bf276d361230
Create Date: 2026-02-10 11:48:30.191169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c579c861c3'
down_revision = 'bf276d361230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('interview_status')

    # ### end Alembic commands ###
