"""Enforce mandatory supplier_id

Revision ID: 54edd737ec83
Revises: 707a1eb8998b
Create Date: 2026-02-18 13:54:02.317992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54edd737ec83'
down_revision = '707a1eb8998b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
