"""Add Supplier model and links

Revision ID: 707a1eb8998b
Revises: b7afed4cfd29
Create Date: 2026-02-18 13:29:39.590196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707a1eb8998b'
down_revision = 'b7afed4cfd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['supplier_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['supplier_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    op.drop_table('suppliers')
    # ### end Alembic commands ###
