"""sync_missing_tables_and_columns

Revision ID: 9db8d0dcd9f1
Revises: daee88220476
Create Date: 2026-09-28 10:13:35.219432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9db8d0dcd9f1'
down_revision = 'daee88220476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('variant_size', sa.String(length=50), nullable=True),
    sa.Column('sku_code', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('stock_quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('gst_percent', sa.Float(), nullable=True),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_b1g1', sa.Boolean(), nullable=True),
    sa.Column('min_threshold', sa.Integer(), nullable=True),
    sa.Column('max_threshold', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('variant_id'),
    sa.UniqueConstraint('sku_code')
    )
    op.drop_table('inventory')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('announcements_created_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('announcements_branch_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['user_id'])
        batch_op.drop_column('priority')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('created_by')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('type')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['variant_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('products_sku_key'), type_='unique')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('sku')
        batch_op.drop_column('mfg_date')
        batch_op.drop_column('barcode')
        batch_op.drop_column('cost_price')

    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('stock_transfers_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['variant_id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'product_variants', ['variant_id'], ['variant_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('must_reset_password', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('upi_id')
        batch_op.drop_column('must_reset_password')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('stock_transfers_product_id_fkey'), 'products', ['product_id'], ['product_id'])
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.drop_column('discount')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mfg_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('products_sku_key'), ['sku'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('unit')

    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('upi_id')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('announcements_branch_id_fkey'), 'branches', ['branch_id'], ['branch_id'])
        batch_op.create_foreign_key(batch_op.f('announcements_created_by_fkey'), 'users', ['created_by'], ['user_id'])
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('target_role')

    op.create_table('inventory',
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('inventory_branch_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('inventory_product_id_fkey')),
    sa.PrimaryKeyConstraint('inventory_id', name=op.f('inventory_pkey'))
    )
    op.drop_table('product_variants')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
