"""add bank details to user

Revision ID: 9dbb627ffeff
Revises: f2f32ddb0f42
Create Date: 2026-02-11 21:35:37.010455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbb627ffeff'
down_revision = 'f2f32ddb0f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
