"""add_sales_id_fields

Revision ID: a63cdde23658
Revises: 54edd737ec83
Create Date: 2026-02-18 14:29:49.365047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63cdde23658'
down_revision = '54edd737ec83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_code', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['branch_code'])

    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('transaction_uuid')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('branch_code')

    # ### end Alembic commands ###
