"""add mfg_date to products

Revision ID: b7afed4cfd29
Revises: 9dbb627ffeff
Create Date: 2026-02-18 10:27:29.482676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7afed4cfd29'
down_revision = '9dbb627ffeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfg_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('mfg_date')

    # ### end Alembic commands ###
