"""Add customer_mobile to sales transactions

Revision ID: b7c881cd8ec8
Revises: e262c5109dec
Create Date: 2026-03-07 22:11:44.552131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c881cd8ec8'
down_revision = 'e262c5109dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_mobile', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.drop_column('customer_mobile')

    # ### end Alembic commands ###
