"""add_global_hr_fields

Revision ID: daee88220476
Revises: 0dd4309dcfce
Create Date: 2026-04-14 00:05:11.273562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daee88220476'
down_revision = '0dd4309dcfce'
branch_labels = None
depends_on = None


def upgrade():
    # Create announcements table if it doesn't exist yet
    # (it was missing from the initial schema migration)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'announcements' not in inspector.get_table_names():
        op.create_table(
            'announcements',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=200), nullable=False),
            sa.Column('message', sa.Text(), nullable=False),
            sa.Column('type', sa.String(length=50), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True,
                      server_default=sa.text("'published'")),
            sa.Column('priority', sa.String(length=20), nullable=True),
            sa.Column('created_by', sa.Integer(), nullable=True),
            sa.Column('branch_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
            sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'published'::character varying"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('joining_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('pan_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('national_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('national_id')
        batch_op.drop_column('pan_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('joining_date')
        batch_op.drop_column('dob')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'published'::character varying"))

    # ### end Alembic commands ###
