"""set_sales_id_nullable_false

Revision ID: e262c5109dec
Revises: a63cdde23658
Create Date: 2026-02-18 14:31:22.777699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e262c5109dec'
down_revision = 'a63cdde23658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('branch_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('branch_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
