"""Add interviewer_id to User

Revision ID: f2f32ddb0f42
Revises: 9976ccf06015
Create Date: 2026-02-10 12:06:03.000167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f32ddb0f42'
down_revision = '9976ccf06015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interviewer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['interviewer_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('interviewer_id')

    # ### end Alembic commands ###
