import React, { useState, useEffect } from 'react';
import { adminApi } from '../../services/api';
import { useToast } from '../ToastContext';

const AIAnnouncementReview = () => {
  const [drafts, setDrafts] = useState([]);
  const [loading, setLoading] = useState(true);
  const { showToast } = useToast();

  useEffect(() => {
    fetchDrafts();
  }, []);

  const fetchDrafts = async () => {
    try {
      const response = await adminApi.getDraftAnnouncements();
      setDrafts(response.drafts || []);
    } catch (error) {
      showToast('Failed to fetch drafts', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handlePublish = async (id) => {
    try {
      await adminApi.publishAnnouncement(id);
      showToast('Announcement published!', 'success');
      fetchDrafts();
    } catch (error) {
      showToast('Failed to publish', 'error');
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this draft?')) return;
    try {
      await adminApi.deleteAnnouncement(id);
      showToast('Draft deleted', 'success');
      fetchDrafts();
    } catch (error) {
      showToast('Failed to delete', 'error');
    }
  };

  const handleManualTrigger = async () => {
    setLoading(true);
    try {
      await adminApi.triggerAIAnnouncements();
      showToast('AI analysis triggered. New drafts may appear.', 'success');
      fetchDrafts();
    } catch (error) {
      showToast('Failed to trigger AI', 'error');
    } finally {
      setLoading(false);
    }
  };

  if (loading && drafts.length === 0) return (
    <div style={{ padding: '24px', color: '#94a3b8', fontSize: '14px', textAlign: 'center' }}>
      <i className="fas fa-circle-notch fa-spin" style={{ marginRight: '8px' }}></i>
      AI Analysis in progress...
    </div>
  );

  return (
    <div style={{ 
      backgroundColor: '#fff', 
      borderRadius: '20px', 
      padding: '28px', 
      border: '1px solid #e2e8f0', 
      boxShadow: '0 4px 20px -5px rgba(0,0,0,0.05)'
    }}>
      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'space-between', 
        marginBottom: '28px',
        paddingBottom: '20px',
        borderBottom: '1px solid #f1f5f9'
      }}>
        <div>
          <h3 style={{ margin: 0, fontSize: '20px', fontWeight: 800, color: '#1e293b', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span style={{ 
              background: 'linear-gradient(135deg, #6366f1, #a855f7)', 
              WebkitBackgroundClip: 'text', 
              WebkitTextFillColor: 'transparent',
              fontSize: '24px'
            }}>🤖</span> 
            AI Review
          </h3>
          <p style={{ margin: '4px 0 0', fontSize: '12px', color: '#64748b', fontWeight: 500 }}>
            Announcements generated by AI pending your approval
          </p>
        </div>
        <button 
          onClick={handleManualTrigger}
          disabled={loading}
          style={{ 
            padding: '12px 24px', 
            background: loading ? '#94a3b8' : 'linear-gradient(135deg, #4338ca, #6366f1)', 
            color: '#fff', 
            border: 'none', 
            borderRadius: '12px', 
            fontSize: '13px', 
            fontWeight: 800, 
            cursor: loading ? 'not-allowed' : 'pointer',
            boxShadow: '0 4px 12px rgba(67, 56, 202, 0.25)',
            letterSpacing: '0.5px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            transition: 'all 0.2s ease'
          }}
          onMouseEnter={(e) => !loading && (e.currentTarget.style.transform = 'translateY(-1px)')}
          onMouseLeave={(e) => !loading && (e.currentTarget.style.transform = 'translateY(0)')}
        >
          {loading ? (
            <i className="fas fa-spinner fa-spin"></i>
          ) : (
            <i className="fas fa-bolt"></i>
          )}
          {loading ? 'Analyzing...' : 'Trigger AI Review'}
        </button>
      </div>

      {drafts.length === 0 ? (
        <div style={{ 
          textAlign: 'center', 
          padding: '48px 20px', 
          backgroundColor: '#f8fafc', 
          borderRadius: '16px', 
          border: '1px dashed #cbd5e1' 
        }}>
          <div style={{ fontSize: '32px', marginBottom: '12px', opacity: 0.5 }}>✨</div>
          <p style={{ margin: 0, color: '#64748b', fontWeight: 600, fontSize: '15px' }}>Systems Optimal</p>
          <p style={{ margin: '6px 0 0', color: '#94a3b8', fontSize: '13px' }}>
            No internal announcements are currently recommended by the AI.
          </p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {drafts.map((draft) => (
            <div key={draft.id} style={{ 
              padding: '24px', 
              backgroundColor: '#fff', 
              borderRadius: '16px', 
              border: '1px solid #f1f5f9', 
              boxShadow: '0 2px 4px rgba(0,0,0,0.02)',
              position: 'relative',
              transition: 'all 0.3s ease',
              borderLeft: '4px solid #f1f5f9'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = '#e0e7ff';
              e.currentTarget.style.borderLeftColor = '#6366f1';
              e.currentTarget.style.boxShadow = '0 10px 15px -3px rgba(0,0,0,0.04)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = '#f1f5f9';
              e.currentTarget.style.borderLeftColor = '#f1f5f9';
              e.currentTarget.style.boxShadow = '0 2px 4px rgba(0,0,0,0.02)';
            }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px' }}>
                <div>
                  <h4 style={{ margin: 0, color: '#1e293b', fontSize: '17px', fontWeight: 800 }}>{draft.title}</h4>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginTop: '6px' }}>
                    <span style={{ 
                      fontSize: '10px', 
                      fontWeight: 800, 
                      color: '#6366f1', 
                      background: '#eff6ff', 
                      padding: '2px 10px', 
                      borderRadius: '9999px',
                      textTransform: 'uppercase',
                      letterSpacing: '0.05em'
                    }}>
                      {draft.target_role?.toUpperCase()}
                    </span>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: '10px' }}>
                  <button 
                    onClick={() => handleDelete(draft.id)}
                    style={{ 
                      padding: '8px 16px', 
                      background: '#fee2e2', 
                      color: '#ef4444', 
                      border: 'none', 
                      borderRadius: '10px', 
                      fontSize: '12px', 
                      fontWeight: 800, 
                      cursor: 'pointer' 
                    }}
                  >
                    Discard
                  </button>
                  <button 
                    onClick={() => handlePublish(draft.id)}
                    style={{ 
                      padding: '8px 16px', 
                      background: '#dcfce7', 
                      color: '#16a34a', 
                      border: 'none', 
                      borderRadius: '10px', 
                      fontSize: '12px', 
                      fontWeight: 800, 
                      cursor: 'pointer' 
                    }}
                  >
                    Post News
                  </button>
                </div>
              </div>

              <div style={{ 
                backgroundColor: '#f8fafc', 
                padding: '16px', 
                borderRadius: '12px', 
                border: '1px solid #f1f5f9',
                color: '#475569',
                fontSize: '14px',
                lineHeight: '1.6',
                whiteSpace: 'pre-wrap'
              }}>
                {draft.message}
              </div>

              <div style={{ 
                marginTop: '16px', 
                display: 'flex', 
                justifyContent: 'space-between', 
                alignItems: 'center',
                fontSize: '11px', 
                color: '#94a3b8',
                fontWeight: 600
              }}>
                <span><i className="fas fa-clock" style={{ marginRight: '6px' }}></i>Drafted {new Date(draft.created_at).toLocaleDateString()}</span>
                <span style={{ color: '#6366f1', cursor: 'pointer' }}>Edit Drafted Content →</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default AIAnnouncementReview;
